### ISSUE TITLE
优化本仓库大小的建议

### ISSUE THREAD

**Issue by lleiwang** [chengxy-nds/Springboot-Notebook#20]
本仓库使用 git 拉取半天才拉取下来，仓库大小为 700MB +
建议 Repo 主优化仓库大小：

- 【 600+MB】优化历史提交记录(.git文件夹)  Ref: https://blog.csdn.net/Y0W1as5eg37urFdS/article/details/123539994
- 【40+MB】删除 eureka-server jar 包 /[springboot-seata-transaction](https://github.com/chengxy-nds/Springboot-Notebook/tree/master/springboot-seata-transaction)/[eureka-server](https://github.com/chengxy-nds/Springboot-Notebook/tree/master/springboot-seata-transaction/eureka-server)/target

Thx~

**Comment by goingboy** [comment]
我看到您加密的代码如下：
public void encrypt(ProceedingJoinPoint joinPoint) {

        try {
            Object[] objects = joinPoint.getArgs();
            if (objects.length != 0) {
                for (Object o : objects) {
                    if (o instanceof String) {
                        encryptValue(o);
                    } else {
                        handler(o, ENCRYPT);
                    }
                    //TODO 其余类型自己看实际情况加
                }
            }
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }
这块是否缺少对EncryptMethod这个注解的参数是否带有EncryptField 进行判断呢？我理解应该是，有带EncryptField 注解的参数才加密，没有的不用加密。
希望您能解答，谢谢！
